[package]
name = "yelling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quark = { path = "../quark" }
camino = "1.1.1"
eyre = "0.6.8"
bempline = { path = "../bempline" }
confindent = "2.2.0"